# fly.toml app configuration file generated for ocontext-quiet-brook-2996 on 2023-11-22T05:37:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ocontext"
primary_region = "ord"

[build]
  image = "ocontext-web:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
